language: dart

dart:
  - dev

env:
  DART_VM_OPTIONS: --enable-experiment=non-nullable

jobs:
  include:
  - dart: dev
    dart_task: test
    os: linux
  - dart: dev
    dart_task: test
    os: windows
  - dart: dev
    dart_task: test
    os: osx
  - dart_task: dartfmt
  - dart_task:
      dartanalyzer: --enable-experiment=non-nullable --fatal-infos --fatal-warnings .
  allow_failures:
  - dart: dev
    dart_task:
      test: -p chrome
    os: linux

# Only building master means that we don't run two builds for each pull request.
# Temporarily adding `null_safety`
branches:
  only: [master, null_safety]

cache:
 directories:
   - $HOME/.pub-cache
